sudo: required
language: generic

services: 
  - docker

before_install: 
  - docker build -t sgaurang82/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sgaurang82/docker-react npm run test